server:
  port: 8007

spring:
  application:
    name: msvc-payment

  datasource:
    url: jdbc:h2:file:./data/payment_db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console


  jwt:
    secret: EstaEsUnaClaveSecretaSuperSeguraYLargaDeAlMenos32Caracteres

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /docs/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true